server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdojo_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
